import { Appeal } from '@/components/features/appeal/data-table/columns'

export const appleals: Appeal[] = [
  {
    id: '1',
    taxYear: 2024,
    company: 'TechNova LLC',
    state: 'CA',
    assessor: 'John Smith',
    accountNumber: 'AC12345',
    appealedDeadline: new Date('2025-03-01'),
    status: 'sent',
    appealedDate: new Date('2025-02-15'),
    appealedBy: 'Alice Johnson',
  },
  {
    id: '2',
    taxYear: 2023,
    company: 'GreenVolt Inc',
    state: 'TX',
    assessor: 'Emma Brown',
    accountNumber: 'TX98765',
    appealedDeadline: new Date('2024-04-15'),
    status: 'not sent',
    appealedDate: new Date('2025-04-10'),
    appealedBy: '',
  },
  {
    id: '3',
    taxYear: 2024,
    company: 'SkyBridge Corp',
    state: 'NY',
    assessor: 'Michael Doe',
    accountNumber: 'NY65432',
    appealedDeadline: new Date('2025-01-20'),
    status: 'sent',
    appealedDate: new Date('2025-01-10'),
    appealedBy: 'Robert Lee',
  },
  {
    id: '4',
    taxYear: 2022,
    company: 'Oceanic Ltd',
    state: 'FL',
    assessor: 'Sophia Davis',
    accountNumber: 'FL43210',
    appealedDeadline: new Date('2023-12-01'),
    status: 'sent',
    appealedDate: new Date('2023-11-20'),
    appealedBy: 'Mark Anderson',
  },
  {
    id: '5',
    taxYear: 2023,
    company: 'InnovaTech',
    state: 'WA',
    assessor: 'Chris Thomas',
    accountNumber: 'WA11223',
    appealedDeadline: new Date('2024-02-10'),
    status: 'not sent',
    appealedDate: new Date('2025-04-10'),
    appealedBy: '',
  },
  {
    id: '6',
    taxYear: 2024,
    company: 'SolarSphere',
    state: 'NV',
    assessor: 'Angela Green',
    accountNumber: 'NV66778',
    appealedDeadline: new Date('2025-03-12'),
    status: 'sent',
    appealedDate: new Date('2025-02-25'),
    appealedBy: 'Derek White',
  },
  {
    id: '7',
    taxYear: 2023,
    company: 'NextGen Systems',
    state: 'IL',
    assessor: 'Bruce Miller',
    accountNumber: 'IL33221',
    appealedDeadline: new Date('2024-06-30'),
    status: 'not sent',
    appealedDate: new Date('2025-04-10'),
    appealedBy: '',
  },
  {
    id: '8',
    taxYear: 2022,
    company: 'EcoBuild',
    state: 'OR',
    assessor: 'Julie Scott',
    accountNumber: 'OR22456',
    appealedDeadline: new Date('2023-09-20'),
    status: 'sent',
    appealedDate: new Date('2023-09-01'),
    appealedBy: 'Tommy Ng',
  },
  {
    id: '9',
    taxYear: 2024,
    company: 'BrightPeak',
    state: 'AZ',
    assessor: 'Ethan Long',
    accountNumber: 'AZ11900',
    appealedDeadline: new Date('2025-04-01'),
    status: 'sent',
    appealedDate: new Date('2025-03-28'),
    appealedBy: 'Karen Liu',
  },
  {
    id: '10',
    taxYear: 2023,
    company: 'NeuroTech',
    state: 'MA',
    assessor: 'Nancy Adams',
    accountNumber: 'MA55443',
    appealedDeadline: new Date('2024-05-25'),
    status: 'not sent',
    appealedDate: new Date('2025-04-10'),
    appealedBy: '',
  },
  {
    id: '11',
    taxYear: 2023,
    company: 'SmartGrid Co',
    state: 'GA',
    assessor: 'Jackie Chen',
    accountNumber: 'GA10101',
    appealedDeadline: new Date('2024-07-10'),
    status: 'sent',
    appealedDate: new Date('2024-06-15'),
    appealedBy: 'Leo Parker',
  },
  {
    id: '12',
    taxYear: 2022,
    company: 'Altair Energy',
    state: 'CO',
    assessor: 'Kyle Brooks',
    accountNumber: 'CO90876',
    appealedDeadline: new Date('2023-11-05'),
    status: 'not sent',
    appealedDate: new Date('2025-04-10'),
    appealedBy: '',
  },
  {
    id: '13',
    taxYear: 2024,
    company: 'DeltaWorks',
    state: 'NC',
    assessor: 'Olivia White',
    accountNumber: 'NC77889',
    appealedDeadline: new Date('2025-02-28'),
    status: 'sent',
    appealedDate: new Date('2025-02-10'),
    appealedBy: 'Nina Patel',
  },
  {
    id: '14',
    taxYear: 2023,
    company: 'AeroSys',
    state: 'MI',
    assessor: 'Brian Ford',
    accountNumber: 'MI34345',
    appealedDeadline: new Date('2024-04-22'),
    status: 'not sent',
    appealedDate: new Date('2025-04-10'),
    appealedBy: '',
  },
  {
    id: '15',
    taxYear: 2024,
    company: 'Luna Innovations',
    state: 'UT',
    assessor: 'Samantha Hall',
    accountNumber: 'UT56565',
    appealedDeadline: new Date('2025-01-05'),
    status: 'sent',
    appealedDate: new Date('2025-01-01'),
    appealedBy: 'Victor Stone',
  },
  {
    id: '16',
    taxYear: 2022,
    company: 'CoreFusion',
    state: 'NJ',
    assessor: 'Zack Morgan',
    accountNumber: 'NJ77881',
    appealedDeadline: new Date('2023-12-31'),
    status: 'sent',
    appealedDate: new Date('2023-12-20'),
    appealedBy: 'Nora Barnes',
  },
  {
    id: '17',
    taxYear: 2023,
    company: 'OmniData',
    state: 'VA',
    assessor: 'Lisa Monroe',
    accountNumber: 'VA30303',
    appealedDeadline: new Date('2024-06-01'),
    status: 'not sent',
    appealedDate: new Date('2025-04-10'),
    appealedBy: '',
  },
  {
    id: '18',
    taxYear: 2024,
    company: 'CyberEdge',
    state: 'MO',
    assessor: 'Trevor Hunt',
    accountNumber: 'MO44332',
    appealedDeadline: new Date('2025-02-10'),
    status: 'sent',
    appealedDate: new Date('2025-02-05'),
    appealedBy: 'Ali Khan',
  },
  {
    id: '19',
    taxYear: 2023,
    company: 'NanoWave',
    state: 'OH',
    assessor: 'Rachel Cole',
    accountNumber: 'OH99112',
    appealedDeadline: new Date('2024-08-12'),
    status: 'not sent',
    appealedDate: new Date('2025-04-10'),
    appealedBy: '',
  },
  {
    id: '20',
    taxYear: 2022,
    company: 'BlueSpark',
    state: 'MN',
    assessor: 'Jeff Simmons',
    accountNumber: 'MN77883',
    appealedDeadline: new Date('2023-11-01'),
    status: 'sent',
    appealedDate: new Date('2023-10-15'),
    appealedBy: 'Sarah Kim',
  },
  {
    id: '21',
    taxYear: 2023,
    company: 'EcoLogic',
    state: 'PA',
    assessor: 'Harvey Dent',
    accountNumber: 'PA33245',
    appealedDeadline: new Date('2024-06-30'),
    status: 'sent',
    appealedDate: new Date('2024-06-10'),
    appealedBy: 'Janet Wells',
  },
  {
    id: '22',
    taxYear: 2024,
    company: 'Xenon Labs',
    state: 'MI',
    assessor: 'Irene Pope',
    accountNumber: 'MI84838',
    appealedDeadline: new Date('2025-03-31'),
    status: 'not sent',
    appealedDate: new Date('2025-04-10'),
    appealedBy: '',
  },
  {
    id: '23',
    taxYear: 2022,
    company: 'FusionEdge',
    state: 'WI',
    assessor: 'Stacy Grant',
    accountNumber: 'WI12221',
    appealedDeadline: new Date('2023-10-05'),
    status: 'sent',
    appealedDate: new Date('2023-09-30'),
    appealedBy: 'Henry Black',
  },
  {
    id: '24',
    taxYear: 2024,
    company: 'QuantaSoft',
    state: 'NC',
    assessor: 'Tina Snow',
    accountNumber: 'NC93939',
    appealedDeadline: new Date('2025-02-15'),
    status: 'sent',
    appealedDate: new Date('2025-01-30'),
    appealedBy: 'Rita Vale',
  },
  {
    id: '25',
    taxYear: 2023,
    company: 'ArgoDigital',
    state: 'LA',
    assessor: 'William Blake',
    accountNumber: 'LA50505',
    appealedDeadline: new Date('2024-09-01'),
    status: 'not sent',
    appealedDate: new Date('2025-04-10'),
    appealedBy: '',
  },
  {
    id: '26',
    taxYear: 2022,
    company: 'NovaBright',
    state: 'AR',
    assessor: 'Tony Evans',
    accountNumber: 'AR67676',
    appealedDeadline: new Date('2023-07-12'),
    status: 'sent',
    appealedDate: new Date('2023-07-01'),
    appealedBy: 'James Gray',
  },
  {
    id: '27',
    taxYear: 2024,
    company: 'PhotonWave',
    state: 'KY',
    assessor: 'Gary Holt',
    accountNumber: 'KY48484',
    appealedDeadline: new Date('2025-04-01'),
    status: 'sent',
    appealedDate: new Date('2025-03-15'),
    appealedBy: 'Wendy Bloom',
  },
  {
    id: '28',
    taxYear: 2023,
    company: 'ZetaMatrix',
    state: 'OK',
    assessor: 'Laura Pierce',
    accountNumber: 'OK29292',
    appealedDeadline: new Date('2024-10-15'),
    status: 'not sent',
    appealedDate: new Date('2025-04-10'),
    appealedBy: '',
  },
  {
    id: '29',
    taxYear: 2022,
    company: 'HyperTech',
    state: 'SC',
    assessor: 'Ben Cross',
    accountNumber: 'SC91919',
    appealedDeadline: new Date('2023-09-25'),
    status: 'sent',
    appealedDate: new Date('2023-09-10'),
    appealedBy: '',
  },
  {
    id: '30',
    taxYear: 2024,
    company: 'VertexLink',
    state: 'TN',
    assessor: 'Diana Knox',
    accountNumber: 'TN11223',
    appealedDeadline: new Date('2025-04-10'),
    status: 'not sent',
    appealedDate: new Date('2025-07-10'),
    appealedBy: '',
  },
];
